version: '2.2'

services:
  next:
    scale: 10
    image: ghcr.io/3threes/3threes:1.0.0
    ports:
      - 8888:8888
    restart: always
    env_file:
      - .env
      
  redis:
    scale: 1
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:

endpoints:
  labels:
    kubernetes.io/ingress.class: nginx
  rules:
    - path: /
      service: next
      port: 8888
