version: '2.2'

services:
  seongland:
    scale: 9
    image: ghcr.io/seongland/seongland:2.0.10
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
      
  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:

endpoints:
  labels:
    kubernetes.io/ingress.class: nginx
  rules:
    - path: /
      service: seongland
      port: 8000
