name: Deploy Image from Semantic Version

on:
  push:
    tags:
      - ^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        run: |
          cd app
          docker build  -t ghcr.io/3bases/3trees:$VERSION \
          --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
          --build-arg GCLOUD_PROJECT=$GCLOUD_PROJECT \
          --build-arg FIREBASE_COLLECTION_IMAGES=$FIREBASE_COLLECTION_IMAGES \
          --build-arg NOTION_API_AUTH_TOKEN=$NOTION_API_AUTH_TOKEN \
          .
          docker push  ghcr.io/3bases/3trees:$VERSION
          docker tag ghcr.io/3bases/3trees:$VERSION ghcr.io/3bases/3trees:latest
          docker push  ghcr.io/3bases/3trees:latest
