name: Test before render

on:
  push:
    branches-ignore:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GCLOUD_PROJECT: export GCLOUD_PROJECT=${{ secrets.GCLOUD_PROJECT }}
  FIREBASE_COLLECTION_IMAGES: export FIREBASE_COLLECTION_IMAGES=${{ secrets.FIREBASE_COLLECTION_IMAGES }}
  NOTION_API_AUTH_TOKEN: export NOTION_API_AUTH_TOKEN=${{ secrets.NOTION_API_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        run: |
          npm i -g pnpm
          pnpm i
          pnpm build:scripts
